import ContactForm from "@/components/Contact/ContactForm";
import InnerpageHeader from "@/components/general/InnerpageHeader";
import React from "react";

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

const Index = () => {
  return (
    <div className="contact">
      <InnerpageHeader pagetitle="Contact Us"/>
      <ContactForm/>
    </div>
  );
};

export default Index;
