import React from "react";

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

const Index = () => {
  return (
    <div>
      contact
    </div>
  );
};

export default Index;
