import "../styles/globals.css";
import { Providers } from "./providers";
import Ticker from "@/components/layout/Ticker";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Toaster from "@/components/general/Toaster";

export const metadata = {
  title: "Yalla Yums",
  description: "Generated by Clicktap",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <Providers>
          <Ticker />
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
