import "../styles/globals.css";
import { Providers } from "./providers";
import Ticker from "@/components/layout/Ticker";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Toaster from "@/components/general/Toaster";
import ProgressProvider from "@/components/layout/ProgressBar";

export const metadata = {
  title: "Yalla Yum",
  description: "Generated by Clicktap",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/favicon.ico"></link>
      </head>
      <body>
        <ProgressProvider>
          <Toaster />
          <Providers>
            <Ticker />
            <Header />
            {children}
            <Footer />
          </Providers>
        </ProgressProvider>
      </body>
    </html>
  );
}
