import { feedlist } from "@/data/feedlist";
import { reviewDataAR } from "@/data/reviewData";
import Blogs from "@/components/Home/Blogs";
import Banner from "@/components/Home/Banner";
import CustomSlider from "@/components/Home/CustomSlider/CustomSlider";
import InstaFeeds from "@/components/Home/InstaFeeds";
import FeedSlider from "@/components/Home/FeedSlider";
import CategoryList from "@/components/shop/CategoryList";
import { getAllBlogs, getCategories } from "@/cached-requests";
import Link from "next/link";
import { homeBannerSlideAR, slide1AR, slide2AR } from "@/data/slides";
import OurImpactAr from "@/components/Home/OurImpactAr";
import ProductFeatureAR from "@/components/general/ProductFeatureAR";
import StoreFeaturesAR from "@/components/general/StoreFeaturesAR";

export const metadata = {
  title: "Home | Yalla Yum",
  description: "Generated by Clicktap",
};

export default async function HomeAr() {
  const { data: categories } = await getCategories();
  const { data: blogsData } = await getAllBlogs();

  const transformedCategories = categories.map((category) => {
    let newName = category.name.trim().toLowerCase();
    if (newName === "all products") {
      newName = "جميع المنتجات";
    } else if (newName === "first taste") {
      newName = "المذاق الأول";
    } else if (newName === "sets") {
      newName = "مجموعات";
    } else if (newName === "make your mix") {
      newName = "اصنع المزيج الخاص بك";
    }

    return { ...category, name: newName };
  });

  return (
    <>
      <Banner arabic={true} slides={homeBannerSlideAR} />
      <div className="py-10 md:py-20 md:pb-10 px-0 md:px-[5%] mx-auto">
        <Link href={"/shop"}>
          <CategoryList itemCount={4} data={transformedCategories} />
        </Link>
      </div>
      <div className="hidden md:block">
        <OurImpactAr />
      </div>
      <CustomSlider arabic={true} slide1={slide1AR} slide2={slide2AR} />
      <InstaFeeds reviewData={reviewDataAR} arabic={true} />
      <Blogs blogsData={blogsData} />
      <ProductFeatureAR />
      <FeedSlider
        feedlist={feedlist}
        subHead={"يلا يم على الإنستغرام"}
        head={"!أنت + يلا يم"}
        follow={"تابعونا على الإنستغرام"}
      />
      <StoreFeaturesAR />
    </>
  );
}
